---
# tasks file for roles/osp-instance-delete
- os_server_info:
    cloud: ospcloud
    server: "{{ item.0.name }}"
  register: result
  with_subelements:
    - "{{ osp_servers }}"

- debug:
    msg: "{{ result.openstack_servers }}"

- name: Delete Instances
  os_server:
    cloud: ospcloud
    name: "{{ item['id'] }}"
    state: absent
  loop: "{{ result['openstack_servers'] }}"
