---
- hosts: workstation
  tasks:
  - name: OpenStack servers
    os_server_info:
      cloud: ospcloud
      server: 'frontend'
      filters:
        vm_state: active
    register: result
  - debug:
      msg: "{{ result.openstack_servers }}"
    tags:
      - osp.smoke1

  - name: Curl website
    uri:
      url: "http://{{ item.addresses.public_v4 }}"
      return_content: yes
    loop:
      - "{{ result.openstack_servers }}"
    register: webpage
    tags:
      - osp.smoke2

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke3
